# mkdocs.yml

site_name: Volume Alignment with Render
site_url: https://schorb.embl-community.io/volumealign


nav:
    - Home: index.md
    - Setup: x2go.md
    - About: about.md
    - Status: EMBL_render_status.md
    - Code Doc: code.md


theme:
  name: "material"

plugins:
- search
- mkdocstrings


extra_css:
    - extra.css


site_dir: public
