# mkdocs.yml

site_name: Volume Alignment with Render
site_url: https://schorb.embl-community.io/volumealign

theme:
  name: material
  font: false

nav:
    - Home: index.md
    - How to:
        - Use it: usage.md
        - initial setup: remote.md
    - About: about.md
    - Status: EMBL_render_status.md
    - Development:
        - Overview: code.md
        - WebUI: dash.md



plugins:
  - macros


markdown_extensions:
  - codehilite


extra:
  dirs:
    code: https://git.embl.de/schorb/volumealign/


extra_css:
    - extra.css


site_dir: public
