# mkdocs.yml

site_name: Volume Alignment with Render
site_url: https://schorb.embl-community.io/volumealign

theme:
  name: material

nav:
    - Home: index.md
    - Setup: x2go.md
    - About: about.md
    - Status: EMBL_render_status.md
    - Development: code.md



plugins:
  - mkdocstrings:
      custom_templates: templates
      handlers:
          python:
            setup_commands:
              - import create_doc_mock








extra_css:
    - extra.css


site_dir: public
