# mkdocs.yml

site_name: Volume Alignment with Render
site_url: https://schorb.embl-community.io/volumealign

theme:
  name: material

nav:
    - Home: index.md
    - How to:
        - Use it: usage.md
        - initial setup: x2go.md
    - About: about.md
    - Status: EMBL_render_status.md
    - Development:
        - Overview: code.md
        - WebUI: dash.md



plugins:
  - mkdocstrings:
      custom_templates: templates
      handlers:
          python:
            setup_commands:
              - import sys
              - sys.path.append("dash")
              - import findimports
              - import glob
              - from unittest.mock import MagicMock as mock
              - src_dir = 'dash'
              - flist = glob.glob(src_dir+'/**/*.py',recursive=True)
              - imp_list=['unittest.mock.MagicMock','sys']
              - for cfile in flist:
                  c_imps = findimports.find_imports(cfile)

                  for imp in c_imps:
                      if imp.name not in imp_list:
                          imp_list.append(imp.name)
                          sys.modules[imp.name] = mock()

  - macros


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  dirs:
    code: https://git.embl.de/schorb/volumealign/


extra_css:
    - extra.css


site_dir: public
